spring.application.name=job-finder

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=job_bot

# Vector Store
spring.ai.vectorstore.mongodb.collection-name=jobs
spring.ai.vectorstore.mongodb.index-name=vector_index
spring.ai.vectorstore.mongodb.path-name=embedding
spring.ai.vectorstore.mongodb.initialize-schema=true

# Gemini AI
spring.ai.vertex.ai.gemini.api-key=${GEMINI_API_KEY}
spring.ai.vertex.ai.gemini.model=gemini-1.5-flash

# Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}