_spring.application.name_=job-finder
_spring.data.mongodb.uri_=mongodb+srv://abhishek17007a_db_user:e9MR52GPXQUHPlBb@cluster0.1swnhwn.mongodb.net/job_bot?retryWrites=true&w=majority
_spring.data.mongodb.database_=job_bot
_spring.ai.vectorstore.mongodb.collection-name_=jobs
_spring.ai.vectorstore.mongodb.index-name_=vector_index
_spring.ai.vectorstore.mongodb.path-name_=embedding
_spring.ai.vectorstore.mongodb.initialize-schema_=true
_spring.ai.vertex.ai.gemini.api-key_=AIzaSyAak4tZq0UImRmWGh2UOrkI8NY1SfY4KqA
_spring.ai.vertex.ai.gemini.model_=gemini-1.5-flash
_telegram.bot.token_=8469957336:AAEaib74JSHzuqrqyl3TO3UQUsqKPhrMG3E
_telegram.chat.id_=1039604123