spring.application.name=job-finder

spring.data.mongodb.uri=mongodb+srv://abhishek17007a_db_user:e9MR52GPXQUHPlBb@cluster0.1swnhwn.mongodb.net/job_bot?retryWrites=true&w=majority
spring.data.mongodb.database=job_bot

spring.ai.model.embedding=transformers

spring.ai.openai.api-key=AIzaSyAak4tZq0UImRmWGh2UOrkI8NY1SfY4KqA
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-1.5-flash

spring.mvc.throw-exception-if-no-handler-found=true
logging.level.org.springframework.web=DEBUG

telegram.bot.token=8469957336:AAEaib74JSHzuqrqyl3TO3UQUsqKPhrMG3E
telegram.chat.id=1039604123