_spring.application.name_=job-finder
_spring.data.mongodb.uri_=mongodb+srv://abhishek17007a_db_user:e9MR52GPXQUHPlBb@cluster0.1swnhwn.mongodb.net/job_bot?retryWrites=true&w=majority
_spring.data.mongodb.database_=job_bot
_spring.ai.vectorstore.mongodb.collection-name_=jobs
_spring.ai.vectorstore.mongodb.index-name_=vector_index
_spring.ai.vectorstore.mongodb.path-name_=embedding
_spring.ai.vectorstore.mongodb.initialize-schema_=true
spring.ai.openai.api-key=AIzaSyAak4tZq0UImRmWGh2UOrkI8NY1SfY4KqA
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-1.5-flash
_telegram.bot.token_=8469957336:AAEaib74JSHzuqrqyl3TO3UQUsqKPhrMG3E
_telegram.chat.id_=1039604123